
const ListCandidates = [
    { name : "A;akdsl;a"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Bdsl;;aasss"},
    { name : "Cassssssaaa"}
]

export default ListCandidates